import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation object type
interface Translations {
  [key: string]: {
    en: string;
    es: string;
  };
}

// All translations in one place
const translations: Translations = {
  // Navigation
  'nav.features': { en: 'Features', es: 'Características' },
  'nav.howItWorks': { en: 'How It Works', es: 'Cómo Funciona' },
  'nav.pricing': { en: 'Pricing', es: 'Precios' },
  'nav.testimonials': { en: 'Testimonials', es: 'Testimonios' },
  'nav.login': { en: 'Login', es: 'Iniciar Sesión' },
  'nav.getStarted': { en: 'Get Started Free', es: 'Comenzar Gratis' },
  'nav.about': { en: 'About', es: 'Acerca de' },
  'nav.contact': { en: 'Contact', es: 'Contacto' },
  'nav.faq': { en: 'FAQ', es: 'Preguntas Frecuentes' },
  'nav.terms': { en: 'Terms', es: 'Términos' },
  'nav.privacy': { en: 'Privacy', es: 'Privacidad' },
  'nav.dashboard': { en: 'Dashboard', es: 'Panel' },
  'nav.logout': { en: 'Logout', es: 'Cerrar Sesión' },
  'nav.welcome': { en: 'Welcome', es: 'Bienvenido' },
  'nav.employeePanel': { en: 'Employee Panel', es: 'Panel de Empleado' },
  'nav.companyPanel': { en: 'Company Panel', es: 'Panel de Empresa' },
  'nav.operatorPanel': { en: 'Operator Panel', es: 'Panel de Operador' },

  // Landing Page - Hero Section
  'landing.badge': { en: 'VE Designed specifically for Venezuela', es: 'VE Diseñado específicamente para Venezuela' },
  'landing.heroTitle1': { en: 'Instant', es: 'Adelantos de' },
  'landing.heroTitle2': { en: 'Payroll', es: 'Nómina' },
  'landing.heroTitle3': { en: 'Advances', es: 'al Instante' },
  'landing.heroDescription': { 
    en: 'Let your employees access up to 80% of their earned wages in seconds. Compatible with PagoMóvil and all Venezuelan banks.',
    es: 'Permite a tus empleados acceder hasta el 80% de sus salarios devengados en segundos. Compatible con PagoMóvil y todos los bancos venezolanos.'
  },
  'landing.startFree30': { en: 'Start Free 30 Days', es: 'Comenzar Gratis 30 Días' },
  'landing.seeDemo': { en: 'See Demo', es: 'Ver Demo' },
  'landing.integration24h': { en: '24-hour integration', es: 'Integración en 24 horas' },
  'landing.lotttCompliance': { en: 'LOTTT Compliance', es: 'Cumplimiento LOTTT' },
  'landing.support247': { en: '24/7 Support', es: 'Soporte 24/7' },
  // Hero sample card labels
  'landing.sampleEmployeeName': { en: 'María González', es: 'María González' },
  'landing.sampleEmployeeRole': { en: 'Employee', es: 'Empleado' },
  'landing.sampleApproved': { en: 'Approved', es: 'Aprobado' },
  'landing.availableForAdvance': { en: 'Available for advance', es: 'Disponible para adelanto' },
  'landing.earnedSalary15': { en: 'Earned salary (15 days)', es: 'Salario devengado (15 días)' },
  'landing.availablePercent': { en: 'Available (80%)', es: 'Disponible (80%)' },
  'landing.requestAdvanceNow': { en: 'Request advance now', es: 'Solicitar adelanto ahora' },
  'landing.instantBadge': { en: 'Instant', es: 'Instantáneo' },
  'landing.pagoMovilReady': { en: 'PagoMóvil Ready', es: 'Listo para PagoMóvil' },

  // Landing Page - Stats
  'landing.stats.companies': { en: 'Active Companies', es: 'Empresas Activas' },
  'landing.stats.processed': { en: 'Processed Monthly', es: 'Procesados Mensualmente' },
  'landing.stats.employees': { en: 'Registered Employees', es: 'Empleados Registrados' },
  'landing.stats.satisfaction': { en: 'Satisfaction', es: 'Satisfacción' },

  // Landing Page - How it Works
  'landing.howItWorks.title': { en: 'How AvancePay Works', es: 'Cómo Funciona AvancePay' },
  'landing.howItWorks.subtitle': { 
    en: 'A simple and automated process that benefits both companies and employees',
    es: 'Un proceso simple y automatizado que beneficia tanto a empresas como empleados'
  },
  'landing.howItWorks.step1.title': { en: 'Company Registration', es: 'Registro de Empresa' },
  'landing.howItWorks.step1.description': { 
    en: 'The company registers, uploads employee information (salaries, IDs, bank details) and defines advance policies.',
    es: 'La empresa se registra, carga la información de empleados (salarios, cédulas, datos bancarios) y define políticas de adelantos.'
  },
  'landing.howItWorks.step2.title': { en: 'Employee Activation', es: 'Activación de Empleados' },
  'landing.howItWorks.step2.description': { 
    en: 'Employees receive an activation code via SMS/Email and can immediately access advance requests based on their worked days.',
    es: 'Los empleados reciben un código de activación por SMS/Email y pueden acceder inmediatamente a solicitar adelantos según sus días trabajados.'
  },
  'landing.howItWorks.step3.title': { en: 'Automatic Advances', es: 'Adelantos Automáticos' },
  'landing.howItWorks.step3.description': { 
    en: 'Requests are automatically approved if within limit (80% earned). Batch payments at 11:00 AM and 3:00 PM.',
    es: 'Las solicitudes se aprueban automáticamente si están dentro del límite (80% devengado). Pagos en lotes a las 11:00 AM y 3:00 PM.'
  },

  // Landing Page - Features
  'landing.features.title': { en: 'Features Designed for Venezuela', es: 'Características Diseñadas para Venezuela' },
  'landing.features.subtitle': { 
    en: 'LOTTT compliance, complete banking integration and the best experience for employees and companies',
    es: 'Cumplimiento LOTTT, integración bancaria completa y la mejor experiencia para empleados y empresas'
  },
  'landing.features.pagomovil.title': { en: 'PagoMóvil & Banks', es: 'PagoMóvil & Bancos' },
  'landing.features.pagomovil.description': { 
    en: 'Compatible with all Venezuelan banks: Mercantil, Venezuela, Banesco, Provincial and more. Instant PagoMóvil.',
    es: 'Compatible con todos los bancos venezolanos: Mercantil, Venezuela, Banesco, Provincial y más. PagoMóvil instantáneo.'
  },
  'landing.features.compliance.title': { en: 'LOTTT Compliance', es: 'Cumplimiento LOTTT' },
  'landing.features.compliance.description': { 
    en: 'Specifically designed to comply with Venezuelan Labor Law. Automatic KYC and legal reports.',
    es: 'Diseñado específicamente para cumplir con la Ley Orgánica del Trabajo venezolana. KYC automático y reportes legales.'
  },
  'landing.features.batches.title': { en: 'Automatic Batches', es: 'Lotes Automáticos' },
  'landing.features.batches.description': { 
    en: 'Batch processing twice daily (11:00 AM and 3:00 PM) for maximum efficiency and lower operational costs.',
    es: 'Procesamiento en lotes dos veces al día (11:00 AM y 3:00 PM) para máxima eficiencia y menores costos operativos.'
  },

  // Login Page
  'login.title': { en: 'Welcome Back', es: 'Bienvenido de Vuelta' },
  'login.subtitle': { en: 'Sign in to your account', es: 'Inicia sesión en tu cuenta' },
  'login.email': { en: 'Email', es: 'Correo' },
  'login.password': { en: 'Password', es: 'Contraseña' },
  'login.submit': { en: 'Sign In', es: 'Iniciar Sesión' },
  'login.noAccount': { en: "Don't have an account?", es: '¿No tienes una cuenta?' },
  'login.signUp': { en: 'Sign up', es: 'Regístrate' },
  'login.forgot': { en: 'Forgot your password?', es: '¿Olvidaste tu contraseña?' },
  'login.errorTitle': { en: 'Sign-in error', es: 'Error al iniciar sesión' },
  'login.errorDescription': { en: 'Check your credentials', es: 'Revisa tus credenciales' },
  'login.incorrectPassword': { en: 'Incorrect Password', es: 'Contraseña Incorrecta' },
  'login.incorrectPasswordDesc': { en: 'The password you entered is incorrect. Please try again.', es: 'La contraseña que ingresaste es incorrecta. Por favor intenta de nuevo.' },
  'permission.denied.title': { en: 'Access Denied', es: 'Acceso Denegado' },
  'permission.denied.message': { en: 'You do not have permission to access this page.', es: 'No tienes permisos para acceder a esta página.' },
  'permission.denied.employee': { en: 'This page is only accessible to employees. You are currently logged in as a {userRole}.', es: 'Esta página solo es accesible para empleados. Actualmente has iniciado sesión como {userRole}.' },
  'permission.denied.company': { en: 'This page is only accessible to company representatives. You are currently logged in as a {userRole}.', es: 'Esta página solo es accesible para representantes de empresa. Actualmente has iniciado sesión como {userRole}.' },
  'permission.denied.operator': { en: 'This page is only accessible to platform operators. You are currently logged in as a {userRole}.', es: 'Esta página solo es accesible para operadores de plataforma. Actualmente has iniciado sesión como {userRole}.' },
  'permission.denied.contactAdmin': { en: 'Please contact your administrator if you believe this is an error.', es: 'Por favor contacta a tu administrador si crees que esto es un error.' },
  'permission.denied.goBack': { en: 'Go Back', es: 'Volver' },
  'permission.denied.logout': { en: 'Logout', es: 'Cerrar Sesión' },

  // Register Page
  'register.title': { en: 'Create Account', es: 'Crear Cuenta' },
  'register.subtitle': { en: 'Get started with your free account', es: 'Comienza con tu cuenta gratuita' },
  'register.fullName': { en: 'Full Name', es: 'Nombre Completo' },
  'register.email': { en: 'Email', es: 'Correo' },
  'register.password': { en: 'Password', es: 'Contraseña' },
  'register.confirmPassword': { en: 'Confirm Password', es: 'Confirmar Contraseña' },
  'register.userType': { en: 'I am a', es: 'Soy un' },
  'register.employee': { en: 'Employee', es: 'Empleado' },
  'register.company': { en: 'Company', es: 'Compañía' },
  // 'register.company': { en: 'Company Representative', es: 'Representante de Empresa' },

  'register.operator': { en: 'Platform Operator', es: 'Operador de Plataforma' },
  'register.submit': { en: 'Create Account', es: 'Crear Cuenta' },
  'register.hasAccount': { en: 'Already have an account?', es: '¿Ya tienes una cuenta?' },
  'register.signIn': { en: 'Sign in', es: 'Inicia sesión' },
  'register.successTitle': { en: 'Account created. Check your email.', es: 'Cuenta creada. Revisa tu email.' },
  'register.errorTitle': { en: 'Registration error', es: 'Error al registrar' },
  'register.tryAgain': { en: 'Please try again', es: 'Inténtalo de nuevo' },
  'register.companyTab': { en: 'Company', es: 'Empresa' },
  'register.employeeTab': { en: 'Employee', es: 'Empleado' },
  'register.companyNamePlaceholder': { en: 'Company S.A.', es: 'Empresa C.A.' },
  'register.companyEmailLabel': { en: 'Company email', es: 'Correo electrónico' },
  'register.companyPasswordLabel': { en: 'Password', es: 'Contraseña' },
  'register.createCompanyButton': { en: 'Create Company Account', es: 'Crear Cuenta Empresarial' },
  'register.inviteTitle': { en: 'Invitation-based registration', es: 'Registro por invitación' },
  'register.inviteDescription': { en: 'Employees are added by their company. If you work for a company using AvancePay...', es: 'Los empleados son registrados por su empresa. Si trabajas para una empresa que usa AvancePay,' },
  'register.employeeEmailLabel': { en: 'Email', es: 'Correo electrónico' },
  'register.employeePasswordLabel': { en: 'Password', es: 'Contraseña' },
  'register.activateEmployeeCTA': { en: 'Activate Employee Account', es: 'Activar Cuenta de Empleado' },
  'register.activating': { en: 'Activating...', es: 'Activando...' },
  'register.haveAccount': { en: 'Already have an account?', es: '¿Ya tienes cuenta?' },
  'register.loginLink': { en: 'Sign in', es: 'Iniciar sesión' },
  'register.activationCode6Digits': { en: 'Activation code must be exactly 6 digits', es: 'El código de activación debe tener exactamente 6 dígitos' },
  'register.invalidEmailFormat': { en: 'Invalid email format. Entered email: "{email}"', es: 'El formato del email no es válido. Email ingresado: "{email}"' },
  'register.invalidActivationOrEmail': { en: 'Invalid activation code or email does not match. Verify the data provided by your company.', es: 'Código de activación inválido o email no coincide. Verifica los datos proporcionados por tu empresa.' },
  'register.accountAlreadyActivated': { en: 'This account has already been activated', es: 'Esta cuenta ya ha sido activada' },
  'register.employeeActivatedTitle': { en: 'Employee account activated successfully', es: 'Cuenta de empleado activada exitosamente' },
  'register.employeeActivatedDesc': { en: 'Welcome {name}. Check your email to confirm your account.', es: 'Bienvenido {name}. Revisa tu email para confirmar tu cuenta.' },
  'register.activateErrorTitle': { en: 'Error activating account', es: 'Error al activar cuenta' },

  // FAQ Page
  'faq.title': { en: 'Frequently Asked Questions', es: 'Preguntas Frecuentes' },
  'faq.subtitle': { en: 'Everything you need to know about payroll advances', es: 'Todo lo que necesitas saber sobre adelantos de nómina' },
  'faq.categories.employees': { en: 'For Employees', es: 'Para Empleados' },
  'faq.categories.companies': { en: 'For Companies', es: 'Para Empresas' },
  'faq.categories.security': { en: 'Security and Legal', es: 'Seguridad y Legal' },
  'faq.categories.technical': { en: 'Technical and Support', es: 'Técnico y Soporte' },
  'faq.questionsCount': { en: 'questions', es: 'preguntas' },
  'faq.support.title': { en: "Didn't find your answer?", es: '¿No encontraste tu respuesta?' },
  'faq.support.description': { en: 'Our support team is available 24/7 to help you', es: 'Nuestro equipo de soporte está disponible 24/7 para ayudarte' },
  'faq.quickLinks': { en: 'Useful links', es: 'Enlaces útiles' },

  // About Page
  'about.title': { en: 'About AvancePay', es: 'Acerca de AvancePay' },
  'about.subtitle': { en: 'We are a Venezuelan company that democratizes access to salary advances, helping workers and companies have greater financial flexibility.', es: 'Somos una empresa venezolana que democratiza el acceso a adelantos salariales, ayudando a trabajadores y empresas a tener mayor flexibilidad financiera.' },
  'about.badge': { en: '🇻🇪 Made in Venezuela, for Venezuelans', es: '🇻🇪 Hecho en Venezuela, para venezolanos' },
  'about.mission.title': { en: 'Our Mission', es: 'Nuestra Misión' },
  'about.vision.title': { en: 'Our Vision', es: 'Nuestra Visión' },
  'about.values.title': { en: 'Our Values', es: 'Nuestros Valores' },
  'about.values.subtitle': { en: 'The principles that guide every decision we make', es: 'Los principios que guían cada decisión que tomamos' },
  'about.history.title': { en: 'Our Story', es: 'Nuestra Historia' },
  'about.history.subtitle': { en: 'The path towards democratizing salary advances', es: 'El camino hacia la democratización de los adelantos salariales' },
  'about.compliance.title': { en: 'Compliance and Regulations', es: 'Cumplimiento y Regulaciones' },
  'about.compliance.subtitle': { en: 'We operate under the Venezuelan legal framework with the highest standards', es: 'Operamos bajo el marco legal venezolano con los más altos estándares' },
  'about.cta.title': { en: 'Ready to get started?', es: '¿Listo para comenzar?' },
  'about.cta.description': { en: 'Join the companies that already trust AvancePay to provide financial flexibility to their employees', es: 'Únete a las empresas que ya confían en AvancePay para brindar flexibilidad financiera a sus empleados' },
  'about.cta.contact': { en: 'Contact Sales', es: 'Contactar Ventas' },

  // Contact Page
  'contact.title': { en: 'Contact Us', es: 'Contáctanos' },
  'contact.subtitle': { en: 'Have questions about AvancePay? Our team is here to help you. Contact us and we will respond as soon as possible.', es: '¿Tienes preguntas sobre AvancePay? Nuestro equipo está aquí para ayudarte. Contáctanos y te responderemos lo antes posible.' },
  'contact.form.title': { en: 'Send us a message', es: 'Envíanos un mensaje' },
  'contact.form.description': { en: 'Fill out the form and we will get in touch with you', es: 'Completa el formulario y nos pondremos en contacto contigo' },
  'contact.form.fullName': { en: 'Full name *', es: 'Nombre completo *' },
  'contact.form.namePlaceholder': { en: 'Your name', es: 'Tu nombre' },
  'contact.form.emailPlaceholder': { en: 'your@email.com', es: 'tu@email.com' },
  'contact.form.company': { en: 'Company', es: 'Empresa' },
  'contact.form.companyPlaceholder': { en: 'Your company name', es: 'Nombre de tu empresa' },
  'contact.form.phone': { en: 'Phone', es: 'Teléfono' },
  'contact.form.queryType': { en: 'Type of inquiry *', es: 'Tipo de consulta *' },
  'contact.form.queryTypePlaceholder': { en: 'Select the type of inquiry', es: 'Selecciona el tipo de consulta' },
  'contact.form.subject': { en: 'Subject *', es: 'Asunto *' },
  'contact.form.subjectPlaceholder': { en: 'How can we help you?', es: '¿En qué podemos ayudarte?' },
  'contact.form.message': { en: 'Message *', es: 'Mensaje *' },
  'contact.form.messagePlaceholder': { en: 'Tell us more details about your inquiry...', es: 'Cuéntanos más detalles sobre tu consulta...' },
  'contact.form.sending': { en: 'Sending...', es: 'Enviando...' },
  'contact.form.send': { en: 'Send Message', es: 'Enviar Mensaje' },
  'contact.channels.title': { en: 'Contact Channels', es: 'Canales de Contacto' },
  'contact.channels.description': { en: 'Multiple ways to communicate with us', es: 'Múltiples formas de comunicarte con nosotros' },
  'contact.offices.title': { en: 'Our Offices', es: 'Nuestras Oficinas' },
  'contact.offices.description': { en: 'Main locations in Venezuela', es: 'Ubicaciones principales en Venezuela' },
  'contact.responseTime.title': { en: 'Response Times', es: 'Tiempos de Respuesta' },
  'contact.faq.title': { en: 'Looking for quick answers?', es: '¿Buscas respuestas rápidas?' },
  'contact.faq.description': { en: 'Visit our frequently asked questions section where you will find answers to the most common questions about AvancePay.', es: 'Visita nuestra sección de preguntas frecuentes donde encontrarás respuestas a las dudas más comunes sobre AvancePay.' },
  'contact.faq.link': { en: 'View FAQ', es: 'Ver Preguntas Frecuentes' },

  // Terms Page
  'terms.title': { en: 'Terms of Service', es: 'Términos de Servicio' },
  'terms.subtitle': { en: 'Terms and conditions governing the use of the AvancePay platform in Venezuela', es: 'Condiciones y términos que rigen el uso de la plataforma AvancePay en Venezuela' },
  'terms.lastUpdated': { en: 'Last updated: September 2024', es: 'Última actualización: Septiembre 2024' },
  'terms.version': { en: 'Version 1.0', es: 'Versión 1.0' },
  'terms.legalNotice': { en: 'Important Legal Notice', es: 'Aviso Legal Importante' },
  'terms.modifications': { en: 'Modifications to Terms', es: 'Modificaciones a los Términos' },
  'terms.questionsTitle': { en: 'Questions about the Terms?', es: '¿Preguntas sobre los Términos?' },
  'terms.questionsDescription': { en: 'If you have questions about these terms of service, contact our legal team', es: 'Si tienes dudas sobre estos términos de servicio, contacta a nuestro equipo legal' },

  // Privacy Page
  'privacy.title': { en: 'Privacy Policy', es: 'Política de Privacidad' },
  'privacy.subtitle': { en: 'How AvancePay collects, uses and protects your personal information in compliance with Venezuelan data protection laws', es: 'Cómo AvancePay recolecta, usa y protege tu información personal en cumplimiento con las leyes venezolanas de protección de datos' },
  'privacy.commitment': { en: 'Our Commitment:', es: 'Nuestro Compromiso:' },
  'privacy.collection.title': { en: 'Information We Collect', es: 'Información que Recolectamos' },
  'privacy.collection.description': { en: 'We collect only the information necessary to provide our services', es: 'Recolectamos únicamente la información necesaria para proporcionar nuestros servicios' },
  'privacy.usage.title': { en: 'How We Use Your Information', es: 'Cómo Usamos tu Información' },
  'privacy.usage.description': { en: 'Your information is used exclusively for the following purposes', es: 'Tu información se utiliza exclusivamente para los siguientes propósitos' },
  'privacy.security.title': { en: 'Security Measures', es: 'Medidas de Seguridad' },
  'privacy.security.description': { en: 'We implement multiple layers of security to protect your information', es: 'Implementamos múltiples capas de seguridad para proteger tu información' },
  'privacy.sharing.title': { en: 'Information Sharing', es: 'Compartir Información' },
  'privacy.sharing.description': { en: 'When and with whom we share your personal information', es: 'Cuándo y con quién compartimos tu información personal' },
  'privacy.rights.title': { en: 'Your Rights', es: 'Tus Derechos' },
  'privacy.rights.description': { en: 'As a user of AvancePay, you have the following rights over your personal information', es: 'Como usuario de AvancePay, tienes los siguientes derechos sobre tu información personal' },
  'privacy.retention.title': { en: 'Data Retention', es: 'Retención de Datos' },
  'privacy.retention.description': { en: 'How long we keep your personal information', es: 'Cuánto tiempo conservamos tu información personal' },
  'privacy.contact.title': { en: 'Privacy Questions?', es: '¿Preguntas sobre Privacidad?' },
  'privacy.contact.description': { en: 'Our Data Protection Officer is available to resolve any questions about the handling of your personal information.', es: 'Nuestro Oficial de Protección de Datos está disponible para resolver cualquier duda sobre el manejo de tu información personal.' },
  'privacy.contact.dpo': { en: 'Contact DPO', es: 'Contactar DPO' },

  // Not Found Page
  'notFound.title': { en: 'Page Not Found', es: 'Página No Encontrada' },
  'notFound.subtitle': { en: 'The page you are looking for does not exist', es: 'La página que buscas no existe' },
  'notFound.backHome': { en: 'Back to Home', es: 'Volver al Inicio' },

  // Common
  'common.loading': { en: 'Loading...', es: 'Cargando...' },
  'common.error': { en: 'Error', es: 'Error' },
  'common.success': { en: 'Success', es: 'Éxito' },
  'common.cancel': { en: 'Cancel', es: 'Cancelar' },
  'common.save': { en: 'Save', es: 'Guardar' },
  'common.edit': { en: 'Edit', es: 'Editar' },
  'common.delete': { en: 'Delete', es: 'Eliminar' },
  'common.continue': { en: 'Continue', es: 'Continuar' },
  'common.back': { en: 'Back', es: 'Atrás' },
  'common.next': { en: 'Next', es: 'Siguiente' },
  'common.previous': { en: 'Previous', es: 'Anterior' },
  'common.close': { en: 'Close', es: 'Cerrar' },
  'common.open': { en: 'Open', es: 'Abrir' },
  'common.yes': { en: 'Yes', es: 'Sí' },
  'common.no': { en: 'No', es: 'No' },
  'common.pending': { en: 'pending', es: 'pendiente' },
  'common.page': { en: 'Page', es: 'Página' },
  'common.show': { en: 'Show', es: 'Mostrar' },
  'common.view': { en: 'View', es: 'Ver' },
  'common.download': { en: 'Download', es: 'Descargar' },
  'common.downloading': { en: 'Downloading...', es: 'Descargando...' },
  'common.accept': { en: 'Accept', es: 'Aceptar' },
  'common.exportXLS': { en: 'Export XLS', es: 'Exportar XLS' },
  // duplicate removed: common.noDataToExport is defined earlier
  'common.showing': { en: 'Showing', es: 'Mostrando' },
  'common.of': { en: 'of', es: 'de' },
  'common.select': { en: 'Select', es: 'Seleccionar' },
  'common.from': { en: 'From', es: 'Desde' },
  'common.to': { en: 'To', es: 'Hasta' },
  'common.clear': { en: 'Clear', es: 'Limpiar' },
  'common.cancelled': { en: 'Cancelled', es: 'Cancelado' },
  'common.processing': { en: 'Processing', es: 'Procesando' },
  'common.failed': { en: 'Failed', es: 'Fallido' },
  'common.unknown': { en: 'Unknown', es: 'Desconocido' },
  'common.for': { en: 'for', es: 'para' },



  // Dashboard common
  'dashboard.welcome': { en: 'Welcome', es: 'Bienvenido' },
  'dashboard.logout': { en: 'Logout', es: 'Cerrar Sesión' },
  'dashboard.profile': { en: 'Profile', es: 'Perfil' },
  'dashboard.settings': { en: 'Settings', es: 'Configuración' },

  // Language switcher
  'language.english': { en: 'English', es: 'Inglés' },
  'language.spanish': { en: 'Spanish', es: 'Español' },
  'language.switch': { en: 'Switch Language', es: 'Cambiar Idioma' },

  // Dashboard Pages
  'employee.dashboard.title': { en: 'Employee Dashboard', es: 'Panel de Empleado' },
  'company.dashboard.title': { en: 'Company Dashboard', es: 'Panel de Empresa' },
  'operator.dashboard.title': { en: 'Operator Dashboard', es: 'Panel de Operador' },

  // Employee Dashboard
  'employee.welcome': { en: 'Hi, {name}!', es: '¡Hola, {name}!' },
  'employee.panel': { en: 'Employee Panel', es: 'Panel de Empleado' },
  'employee.availableAdvance': { en: 'Available for Advance', es: 'Disponible para Adelanto' },
  'employee.ofEarned': { en: '80% of ${amount} earned', es: '80% de ${amount} devengados' },
  'employee.monthlySalary': { en: 'Monthly Salary', es: 'Salario Mensual' },
  'employee.daysWorked': { en: '{worked} of {total} days worked', es: '{worked} de {total} días trabajados' },
  'employee.advancesUsed': { en: 'Advances Used', es: 'Adelantos Usados' },
  'employee.thisPeriod': { en: 'This period', es: 'Este período' },
  'employee.pending': { en: 'Pending', es: 'Pendientes' },
  'employee.advanceInProcess': { en: 'Advance in process', es: 'Adelanto en proceso' },
  'employee.requestAdvance': { en: 'Request Advance', es: 'Solicitar Adelanto' },
  'employee.requestDescription': { en: 'Request an advance of your earned salary instantly', es: 'Solicita un adelanto de tu salario devengado de forma instantánea' },
  'employee.daysWorkedMonth': { en: 'Days worked this month', es: 'Días trabajados este mes' },
  'employee.days': { en: 'days', es: 'días' },
  'employee.availableAmount': { en: 'Available amount', es: 'Monto disponible' },
  'employee.earnedSalary': { en: 'Earned salary', es: 'Salario devengado' },
  'employee.availableForAdvance': { en: 'Available for advance (80%)', es: 'Disponible para adelanto (80%)' },
  'employee.advanceUsage': { en: 'Advance usage', es: 'Uso de adelantos' },
  'employee.newAdvance': { en: 'New Advance', es: 'Nuevo Adelanto' },
  'employee.requestedAmount': { en: 'Requested amount:', es: 'Monto solicitado:' },
  'employee.maximum': { en: 'Maximum', es: 'Máximo' },
  'employee.nearLimit': { en: 'You are close to your maximum advance limit', es: 'Estás cerca de tu límite máximo de adelanto' },
  'employee.minimumAmount': { en: 'You are requesting a minimum amount', es: 'Estás solicitando un monto mínimo' },
  'employee.minimumAmountDesc': { en: 'Consider requesting a higher amount to maximize your advance benefit', es: 'Considera solicitar un monto mayor para maximizar el beneficio de tu adelanto' },
  'employee.amountToRequest': { en: 'Amount to request', es: 'Monto a solicitar' },
  'employee.grossAmount': { en: 'Gross amount:', es: 'Monto bruto:' },
  'employee.commission': { en: 'Commission (5%):', es: 'Comisión (5%):' },
  'employee.youWillReceive': { en: 'You will receive:', es: 'Recibirás:' },
  'employee.requestButton': { en: 'Request Advance', es: 'Solicitar Adelanto' },
  'employee.autoProcessing': { en: 'Automatic processing', es: 'Procesamiento automático' },
  'employee.quickAmount': { en: 'Quick amount:', es: 'Monto rápido:' },
  'employee.enterCustomAmount': { en: 'Or enter a custom amount:', es: 'O ingresa un monto personalizado:' },
  'employee.afterRequestLeft': { en: 'After this request you will have {amount} USD available', es: 'Después de esta solicitud tendrás {amount} USD disponibles' },
  'employee.usingOfLimit': { en: 'Using of available limit', es: 'Uso del límite disponible' },
  'employee.batchProcessingTitle': { en: 'Batch processing', es: 'Procesamiento por lotes' },
  'employee.batchProcessingDesc': { en: 'Advances are processed manually in two daily batches: 11:00 AM and 3:00 PM. You will receive the money the same day via PagoMóvil or bank transfer.', es: 'Los adelantos se procesan manualmente en dos lotes diarios: 11:00 AM y 3:00 PM. Recibirás el dinero el mismo día por PagoMóvil o transferencia bancaria.' },
  'employee.confirmRequestTitle': { en: 'Confirm Advance Request', es: 'Confirmar Solicitud de Adelanto' },
  'employee.batchProcessingNext': { en: 'Your advance will be processed in the next batch (11:00 AM or 3:00 PM) and you will receive the money the same day.', es: 'Tu adelanto se procesará en el próximo lote (11:00 AM o 3:00 PM) y recibirás el dinero el mismo día.' },
  'employee.confirmRequest': { en: 'Confirm Request', es: 'Confirmar Solicitud' },
  'employee.confirmDialogDesc': { en: 'Please review your request details before confirming.', es: 'Por favor, revisa los detalles de tu solicitud antes de confirmar.' },
  'employee.preApproved': { en: 'Pre-approved request', es: 'Solicitud preaprobada' },
  'employee.preApprovedDesc': { en: 'Your advance was approved and will be processed in the next batch (11:00 AM or 3:00 PM)', es: 'Tu adelanto fue aprobado y será procesado en el próximo lote (11:00 AM o 3:00 PM)' },
  'employee.advanceHistory': { en: 'Advance History', es: 'Historial de Adelantos' },
  'employee.loadingEmployeeData': { en: 'Loading employee data...', es: 'Cargando datos del empleado...' },
  'employee.noDataTitle': { en: 'No data found', es: 'No se encontraron datos' },
  'employee.noDataDesc': { en: 'Employee data could not be loaded.', es: 'No se pudieron cargar los datos del empleado.' },
  'employee.retry': { en: 'Retry', es: 'Reintentar' },
  'employee.cancel': { en: 'Cancel', es: 'Cancelar' },
  'employee.cancelAdvanceTitle': { en: 'Cancel Advance', es: 'Cancelar Adelanto' },
  'employee.cancelAdvanceConfirm': { en: 'Are you sure you want to cancel this advance of ${amount}? This action cannot be undone.', es: '¿Estás seguro de que quieres cancelar este adelanto de ${amount}? Esta acción no se puede deshacer.' },
  'employee.keep': { en: 'No, keep', es: 'No, mantener' },
  'employee.yesCancel': { en: 'Yes, cancel', es: 'Sí, cancelar' },
  'employee.cancelledTitle': { en: 'Advance cancelled', es: 'Adelanto cancelado' },
  'employee.cancelledDesc': { en: 'Your advance request has been cancelled successfully', es: 'Tu solicitud de adelanto ha sido cancelada exitosamente' },
  'employee.couldNotCancel': { en: 'Could not cancel the advance', es: 'No se pudo cancelar el adelanto' },
  'employee.export': { en: 'Export', es: 'Exportar' },
  'employee.inProcess': { en: 'In process', es: 'En proceso' },
  'employee.completed': { en: 'Completed', es: 'Completado' },
  'employee.paymentMethods': { en: 'Payment Methods', es: 'Métodos de Pago' },
  'employee.main': { en: 'Main', es: 'Principal' },
  'employee.backup': { en: 'Backup', es: 'Respaldo' },
  'employee.paymentNote': { en: 'Only your company can modify these payment methods', es: 'Solo tu empresa puede modificar estos métodos de pago' },
  // Company Dashboard - Payment Methods/Billing Info section
  'company.billing.paymentMethodsTitle': { en: 'Payment Methods', es: 'Métodos de Pago' },
  'company.billing.paymentMethodsDesc': { en: 'Payment and billing configuration', es: 'Configuración de pagos y facturación' },
  'company.billing.billingInfo': { en: 'Billing Information', es: 'Información de Facturación' },
  'company.billing.company': { en: 'Company:', es: 'Empresa:' },
  'company.billing.rifLabel': { en: 'RIF:', es: 'RIF:' },
  'company.billing.billingPeriod': { en: 'Billing period:', es: 'Período de facturación:' },
  'company.billing.biweekly': { en: 'Biweekly', es: 'Quincenal' },
  'company.billing.paymentMethodLabelFull': { en: 'Payment method:', es: 'Método de pago:' },
  'company.billing.upcomingPayments': { en: 'Upcoming Payments', es: 'Próximos Pagos' },
  'company.billing.nextInvoice': { en: 'Next invoice:', es: 'Próxima factura:' },
  'company.billing.estimatedAmountShort': { en: 'Estimated amount:', es: 'Monto estimado:' },
  'company.billing.daysRemainingShort': { en: 'Days remaining:', es: 'Días restantes:' },
  'company.billing.daysUnit': { en: 'days', es: 'días' },
  // Company Dashboard - Reports section
  'company.reports.filters': { en: 'Report Filters', es: 'Filtros de Reporte' },
  'company.reports.filtersDesc': { en: 'Select the period and type of report to generate', es: 'Selecciona el período y tipo de reporte que deseas generar' },
  'company.reports.type.advances': { en: 'Advances', es: 'Adelantos' },
  'company.reports.type.fees': { en: 'Commissions and Fees', es: 'Comisiones y Tarifas' },
  'company.reports.type.employees': { en: 'Employees', es: 'Empleados' },
  'company.reports.type.comprehensive': { en: 'Comprehensive Report', es: 'Reporte Completo' },
  'company.reports.generate': { en: 'Generate Report', es: 'Generar Reporte' },
  'company.reports.totalAdvances': { en: 'Total Advances', es: 'Total Adelantos' },
  'company.reports.commissions': { en: 'Commissions', es: 'Comisiones' },
  'company.reports.activeEmployees': { en: 'Active Employees', es: 'Empleados Activos' },
  'company.reports.avgPerEmployee': { en: 'Average per Employee', es: 'Promedio por Empleado' },
  'company.reports.advancesReport': { en: 'Advances Report', es: 'Reporte de Adelantos' },
  'company.reports.advancesReportDesc': { en: 'Detailed analysis of advance requests', es: 'Análisis detallado de solicitudes de adelanto' },
  'company.reports.totalRequests': { en: 'Total requests:', es: 'Total de solicitudes:' },
  'company.reports.approvedRequests': { en: 'Approved requests:', es: 'Solicitudes aprobadas:' },
  'company.reports.pendingRequests': { en: 'Pending requests:', es: 'Solicitudes pendientes:' },
  'company.reports.rejectedRequests': { en: 'Rejected requests:', es: 'Solicitudes rechazadas:' },
  'company.reports.avgAmount': { en: 'Average amount:', es: 'Monto promedio:' },
  'company.reports.exportAdvances': { en: 'Export Advances Report', es: 'Exportar Reporte de Adelantos' },
  'company.reports.usageAnalysis': { en: 'Usage Analysis', es: 'Análisis de Uso' },
  'company.reports.usageAnalysisDesc': { en: 'Participation stats and trends', es: 'Estadísticas de participación y tendencias' },
  'company.reports.exportAnalysis': { en: 'Export Analysis', es: 'Exportar Análisis' },
  // Generic labels used in reports tiles/subtitles
  'company.requests': { en: 'requests', es: 'solicitudes' },
  'company.average': { en: 'average', es: 'promedio' },
  'company.participation': { en: 'participation', es: 'participación' },
  'company.perActiveEmployee': { en: 'per active employee', es: 'por empleado activo' },
  'company.periodLabel': { en: 'Period', es: 'Período' },
  'company.selectPeriod': { en: 'Select period', es: 'Seleccionar período' },
  'company.reportTypeLabel': { en: 'Report Type', es: 'Tipo de Reporte' },
  'company.selectType': { en: 'Select type', es: 'Seleccionar tipo' },
  'company.formatLabel': { en: 'Format', es: 'Formato' },
  'company.selectFormat': { en: 'Select format', es: 'Seleccionar formato' },
  'company.participationRate': { en: 'Participation rate', es: 'Tasa de participación' },
  'company.mostActiveEmployees': { en: 'Most active employees', es: 'Empleados más activos' },
  'company.mostActiveDay': { en: 'Most active day', es: 'Día más activo' },
  'company.peakHour': { en: 'Peak hour', es: 'Horario pico' },
  'company.monthlyGrowth': { en: 'Monthly growth', es: 'Crecimiento mensual' },
  // Period options
  'company.thisMonth': { en: 'This Month', es: 'Este Mes' },
  'company.lastMonth': { en: 'Last Month', es: 'Mes Pasado' },
  'company.last3Months': { en: 'Last 3 Months', es: 'Últimos 3 Meses' },
  'company.last6Months': { en: 'Last 6 Months', es: 'Últimos 6 Meses' },
  'company.thisYear': { en: 'This Year', es: 'Este Año' },
  'company.custom': { en: 'Custom', es: 'Personalizado' },
  // Common keys for exports / toasts
  'common.noData': { en: 'No data', es: 'No hay datos' },
  'common.noDataToExport': { en: 'There are no advances to export in the selected range', es: 'No hay adelantos para exportar en el rango seleccionado' },
  'common.exportSuccess': { en: 'Export successful', es: 'Exportación exitosa' },
  'common.date': { en: 'Date', es: 'Fecha' },
  'common.employee': { en: 'Employee', es: 'Empleado' },
  'common.requestedAmount': { en: 'Requested Amount', es: 'Monto Solicitado' },
  'common.fee': { en: 'Fee', es: 'Comisión' },
  'common.netAmount': { en: 'Net Amount', es: 'Monto Neto' },
  'common.status': { en: 'Status', es: 'Estado' },
  'common.paymentMethod': { en: 'Payment Method', es: 'Método de Pago' },
  'common.paymentDetails': { en: 'Payment Details', es: 'Detalles de Pago' },
  'common.batch': { en: 'Batch', es: 'Lote' },
  'common.processedAt': { en: 'Processed At', es: 'Fecha de Procesamiento' },
  // Landing page strings (duplicates removed)
  'landing.features.card1.title': { en: 'PagoMóvil & Banks', es: 'PagoMóvil & Bancos' },
  'landing.features.card1.desc': { en: 'Compatible with all Venezuelan banks. Instant PagoMóvil.', es: 'Compatible con todos los bancos venezolanos. PagoMóvil instantáneo.' },
  'landing.features.card2.title': { en: 'LOTTT Compliance', es: 'Cumplimiento LOTTT' },
  'landing.features.card2.desc': { en: 'Designed to comply with Venezuelan labor law. Automated KYC and legal reports.', es: 'Diseñado para cumplir con la ley laboral venezolana. KYC automático y reportes legales.' },
  'landing.features.card3.title': { en: 'Automatic Batches', es: 'Lotes Automáticos' },
  'landing.features.card3.desc': { en: 'Two batch runs per day (11:00 AM and 3:00 PM) for efficiency and lower costs.', es: 'Procesamiento en lotes dos veces al día (11:00 AM y 3:00 PM) para eficiencia y menores costos.' },
  'landing.features.card4.title': { en: 'Business Analytics', es: 'Analytics Empresarial' },
  'landing.features.card4.desc': { en: 'Full dashboard with usage metrics, cash flow analysis and satisfaction reports.', es: 'Dashboard con métricas de uso, análisis de flujo de caja y reportes de satisfacción.' },
  'landing.features.card5.title': { en: 'Automated Reports', es: 'Reportes Automáticos' },
  'landing.features.card5.desc': { en: 'Automatic CSV/Excel exports for payroll systems. Perfect reconciliation.', es: 'Exportación automática CSV/Excel para nómina. Conciliación perfecta.' },
  'landing.features.card6.title': { en: 'Smart Limits', es: 'Límites Inteligentes' },
  'landing.features.card6.desc': { en: 'Eligibility based on worked days. Up to 80% of earned wages.', es: 'Elegibilidad basada en días trabajados. Hasta 80% del salario devengado.' },
  // Landing - Testimonials
  'landing.testimonials.title': { en: 'What Our Customers Say', es: 'Lo Que Dicen Nuestros Clientes' },
  'landing.testimonials.subtitle': { en: 'Venezuelan companies that already transformed their payroll with AvancePay', es: 'Empresas venezolanas que ya transformaron su nómina con AvancePay' },
  'landing.testimonials.card1.name': { en: 'Carlos Mendoza', es: 'Carlos Mendoza' },
  'landing.testimonials.card1.role': { en: 'HR Director, TechVenezuela C.A.', es: 'Director de RRHH, TechVenezuela C.A.' },
  'landing.testimonials.card1.quote': { en: 'AvancePay significantly improved our employees\' satisfaction. Implementation was super fast and the technical support is exceptional.', es: 'AvancePay mejoró significativamente la satisfacción de nuestros empleados. La implementación fue súper rápida y el soporte técnico es excepcional.' },
  'landing.testimonials.card2.name': { en: 'María Rodríguez', es: 'María Rodríguez' },
  'landing.testimonials.card2.role': { en: 'Employee, Financial Services', es: 'Empleada, Servicios Financieros' },
  'landing.testimonials.card2.quote': { en: 'It\'s amazing to access my salary when I need it. The process is super easy and the money arrives to my PagoMóvil in minutes.', es: 'Es increíble poder acceder a mi salario cuando lo necesito. El proceso es súper fácil y el dinero llega a mi PagoMóvil en minutos.' },
  'landing.testimonials.card3.name': { en: 'José Silva', es: 'José Silva' },
  'landing.testimonials.card3.role': { en: 'CEO, Industrias del Zulia', es: 'CEO, Industrias del Zulia' },
  'landing.testimonials.card3.quote': { en: 'Weekly reports greatly simplify our payroll management. AvancePay integrated perfectly with our existing processes.', es: 'Los reportes semanales facilitan muchísimo nuestra gestión de nómina. AvancePay se integró perfectamente con nuestros procesos existentes.' },
  // Landing - Pricing
  'landing.pricing.title': { en: 'Clear and Fair Pricing', es: 'Precios Claros y Justos' },
  'landing.pricing.subtitle': { en: 'No fine print. No hidden fees. Pay only for what you use with automated weekly billing.', es: 'Sin letra pequeña. Sin costos ocultos. Solo paga por lo que usas con facturación semanal automatizada.' },
  'landing.pricing.planCompany.title': { en: 'For Companies', es: 'Para Empresas' },
  'landing.pricing.planCompany.priceNote': { en: 'per active employee / month', es: 'por empleado activo / mes' },
  'landing.pricing.company.b1': { en: 'Full business dashboard with analytics', es: 'Dashboard empresarial completo con analytics' },
  'landing.pricing.company.b2': { en: 'Automated CSV/Excel payroll reports', es: 'Reportes CSV/Excel automatizados para nómina' },
  'landing.pricing.company.b3': { en: 'Complete employee and payment methods management', es: 'Gestión completa de empleados y métodos de pago' },
  'landing.pricing.company.b4': { en: 'Priority 24/7 technical support', es: 'Soporte técnico prioritario 24/7' },
  'landing.pricing.company.b5': { en: 'Weekly billing with automatic reconciliation', es: 'Facturación semanal con conciliación automática' },
  'landing.pricing.company.b6': { en: 'LOTTT compliance and legal reports', es: 'Cumplimiento LOTTT y reportes legales' },
  'landing.pricing.company.example': { en: 'Practical example: Company with 50 employees = $50/month', es: 'Ejemplo práctico: Empresa con 50 empleados = $50/mes' },
  'landing.pricing.company.cta': { en: 'Start Free Trial', es: 'Comenzar Prueba Gratis' },
  'landing.pricing.badge': { en: 'Zero cost for companies', es: 'Costo cero para empresas' },
  'landing.pricing.planEmployee.title': { en: 'For Employees', es: 'Para Empleados' },
  'landing.pricing.employee.priceNote': { en: 'per advance (min. $1, max. $20)', es: 'por adelanto (mín. $1, máx. $20)' },
  'landing.pricing.employee.b1': { en: 'Access up to 80% of earned wages', es: 'Acceso hasta 80% del salario devengado' },
  'landing.pricing.employee.b2': { en: 'Advances processed in batches (11 AM and 3 PM)', es: 'Adelantos procesados en lotes (11 AM y 3 PM)' },
  'landing.pricing.employee.b3': { en: 'PagoMóvil and transfers to any bank', es: 'PagoMóvil y transferencias a cualquier banco' },
  'landing.pricing.employee.b4': { en: 'Mobile app and responsive web', es: 'App móvil y web responsive' },
  'landing.pricing.employee.b5': { en: 'Full advance history', es: 'Historial completo de adelantos' },
  'landing.pricing.employee.b6': { en: 'Automatic eligibility calculation', es: 'Cálculo automático de elegibilidad' },
  'landing.pricing.employee.example': { en: 'Example: $100 advance → You receive $95 (fee $5)', es: 'Ejemplo: Adelanto de $100 → Recibes $95 (comisión $5)' },
  'landing.pricing.employee.cta': { en: 'Activate My Account', es: 'Activar Mi Cuenta' },
  // Landing - Enterprise banner
  'landing.enterprise.title': { en: 'Large companies?', es: '¿Empresas grandes?' },
  'landing.enterprise.subtitle': { en: 'Custom enterprise plans for 500+ employees with special discounts and advanced features.', es: 'Planes empresariales personalizados para +500 empleados con descuentos especiales y características avanzadas.' },
  'landing.enterprise.contactSales': { en: 'Contact Enterprise Sales', es: 'Contactar Ventas Empresariales' },
  // Landing - CTA
  'landing.cta.title': { en: 'Ready to Revolutionize Your Payroll?', es: '¿Listo para Revolucionar tu Nómina?' },
  'landing.cta.subtitle': { en: 'Join 150+ Venezuelan companies improving employee satisfaction and simplifying advance management.', es: 'Únete a más de 150 empresas venezolanas que ya mejoraron la satisfacción de sus empleados y simplificaron su gestión de adelantos salariales.' },
  'landing.cta.startTrial': { en: 'Start Free Trial', es: 'Comenzar Prueba Gratuita' },
  'landing.cta.haveAccount': { en: 'I have an account', es: 'Tengo una Cuenta' },
  'landing.cta.metric30': { en: '30 days', es: '30 días' },
  'landing.cta.metric30Label': { en: 'Completely free trial', es: 'Prueba completamente gratis' },
  'landing.cta.metric24h': { en: '24 hours', es: '24 horas' },
  'landing.cta.metric24hLabel': { en: 'Implementation time', es: 'Tiempo de implementación' },
  'landing.cta.metric247': { en: '24/7', es: '24/7' },
  'landing.cta.metric247Label': { en: 'Technical support included', es: 'Soporte técnico incluido' },
  // Landing - Footer
  'footer.description': { en: 'The first Venezuelan earned wage access platform designed to comply with LOTTT and optimize the experience for employees and companies.', es: 'La primera plataforma venezolana de adelantos salariales diseñada específicamente para cumplir con LOTTT y optimizar la experiencia de empleados y empresas.' },
  'footer.product': { en: 'Product', es: 'Producto' },
  'footer.product.features': { en: 'Features', es: 'Características' },
  'footer.product.pricing': { en: 'Pricing', es: 'Precios' },
  'footer.product.liveDemo': { en: 'Live Demo', es: 'Demo en Vivo' },
  'footer.product.integrations': { en: 'Integrations', es: 'Integraciones' },
  'footer.product.api': { en: 'API', es: 'API' },
  'footer.company': { en: 'Company', es: 'Empresa' },
  'footer.company.about': { en: 'About AvancePay', es: 'Sobre AvancePay' },
  'footer.company.team': { en: 'Our Team', es: 'Nuestro Equipo' },
  'footer.company.careers': { en: 'Careers', es: 'Carreras' },
  'footer.company.contact': { en: 'Contact', es: 'Contacto' },
  'footer.company.press': { en: 'Press', es: 'Prensa' },
  'footer.support': { en: 'Support', es: 'Soporte' },
  'footer.support.helpCenter': { en: 'Help Center', es: 'Centro de Ayuda' },
  'footer.support.docs': { en: 'Documentation', es: 'Documentación' },
  'footer.support.status': { en: 'System Status', es: 'Estado del Sistema' },
  'footer.support.terms': { en: 'Terms of Use', es: 'Términos de Uso' },
  'footer.support.privacy': { en: 'Privacy', es: 'Privacidad' },
  'footer.copyright': { en: 'All rights reserved.', es: 'Todos los derechos reservados.' },
  'footer.madeInVe': { en: 'Made with ❤️ in Venezuela', es: 'Hecho con ❤️ en Venezuela' },
  'footer.lotttBadge': { en: 'LOTTT Compliance', es: 'Cumplimiento LOTTT' },
  'employee.nextPayroll': { en: 'Next Payroll', es: 'Próxima Nómina' },
  'employee.willDeduct': { en: 'Will deduct', es: 'Se descontarán' },
  'employee.advances': { en: 'advances', es: 'de adelantos' },
  'employee.needHelp': { en: 'Need help?', es: '¿Necesitas ayuda?' },
  'employee.supportDescription': { en: 'Our team is available to resolve your questions', es: 'Nuestro equipo está disponible para resolver tus dudas' },
  'employee.contactSupport': { en: 'Contact Support', es: 'Contactar Soporte' },
  'employee.today': { en: 'Today', es: 'Hoy' },
  'employee.ago': { en: 'ago', es: 'Hace' },
  'employee.week': { en: 'week', es: 'semana' },
  'employee.daysCount': { en: 'days', es: 'días' },

  // Company Dashboard
  'company.panel': { en: 'Company Panel', es: 'Panel Empresarial' },
  'company.configuration': { en: 'Configuration', es: 'Configuración' },
  'company.activeEmployees': { en: 'Active Employees', es: 'Empleados Activos' },
  'company.monthlyFees': { en: 'USD/month in fees', es: 'USD/mes en comisiones' },
  'company.advancesThisMonth': { en: 'Advances This Month', es: 'Adelantos Este Mes' },
  'company.vsLastMonth': { en: 'vs last month', es: 'respecto al mes anterior' },
  'company.pendingApproval': { en: 'Advances awaiting approval', es: 'Adelantos esperando aprobación' },
  'company.pendingApprovalOne': { en: 'Advance awaiting approval', es: 'Adelanto esperando aprobación' },
  'company.pendingApprovalMany': { en: 'Advances awaiting approval', es: 'Adelantos esperando aprobación' },
  'company.weeklyBilling': { en: 'Weekly Billing', es: 'Facturación Semanal' },
  'company.nextBill': { en: 'Next bill:', es: 'Próxima factura:' },
  'company.advances': { en: 'Advances', es: 'Adelantos' },
  'company.employees': { en: 'Employees', es: 'Empleados' },
  'company.reports': { en: 'Reports', es: 'Reportes' },
  'company.billing': { en: 'Billing', es: 'Facturación' },
  'company.recentAdvances': { en: 'Recent Advances', es: 'Adelantos Recientes' },
  'company.manageAdvances': { en: 'Manage advance requests from your employees', es: 'Gestiona las solicitudes de adelanto de tus empleados' },
  'company.filter': { en: 'Filter', es: 'Filtrar' },
  'company.request': { en: 'Request', es: 'Solicitud' },
  'company.reject': { en: 'Reject', es: 'Rechazar' },
  'company.approve': { en: 'Approve', es: 'Aprobar' },
  'company.approved': { en: 'Approved', es: 'Aprobado' },
  'company.employeeManagement': { en: 'Employee Management', es: 'Gestión de Empleados' },
  'company.managePayroll': { en: 'Manage your payroll and registered employees', es: 'Administra tu nómina y empleados registrados' },
  'company.searchEmployee': { en: 'Search employee...', es: 'Buscar empleado...' },
  'company.addEmployee': { en: 'Add Employee', es: 'Agregar Empleado' },
  // Add Employee Modal
  'company.addEmployeeTitle': { en: 'Add New Employee', es: 'Agregar Nuevo Empleado' },
  'company.addEmployeeDesc': { en: 'Fill out the employee information to send an activation code.', es: 'Completa la información del empleado para enviar un código de activación.' },
  // EmployeeInfoForm labels
  'employeeForm.firstName': { en: 'First name', es: 'Nombre' },
  'employeeForm.lastName': { en: 'Last name', es: 'Apellido' },
  'employeeForm.email': { en: 'Email', es: 'Email' },
  'employeeForm.yearOfEmployment': { en: 'Year of employment', es: 'Año de empleo' },
  'employeeForm.weeklyHours': { en: 'Weekly working hours', es: 'Horas de trabajo semanales' },
  'employeeForm.weeklyHoursShort': { en: 'Weekly hours', es: 'Horas semanales' },
  'employeeForm.livingExpenses': { en: 'Monthly living expenses (USD)', es: 'Gastos de vida mensuales (USD)' },
  'employeeForm.birthDate': { en: 'Birth date', es: 'Fecha de nacimiento' },
  'employeeForm.selectDate': { en: 'Select date', es: 'Seleccionar fecha' },
  'employeeForm.position': { en: 'Position', es: 'Cargo' },
  'employeeForm.department': { en: 'Department', es: 'Departamento' },
  'employeeForm.startDate': { en: 'Employment start date', es: 'Fecha de inicio de empleo' },
  'employeeForm.employmentType': { en: 'Employment type', es: 'Tipo de empleo' },
  'employeeForm.selectType': { en: 'Select type', es: 'Seleccionar tipo' },
  'employeeForm.fullTime': { en: 'Full-time', es: 'Tiempo completo' },
  'employeeForm.partTime': { en: 'Part-time', es: 'Medio tiempo' },
  'employeeForm.contract': { en: 'Contract', es: 'Contrato' },
  'employeeForm.monthlySalary': { en: 'Monthly salary (USD)', es: 'Salario mensual (USD)' },
  'employeeForm.dependents': { en: 'Number of dependents', es: 'Número de dependientes' },
  'employeeForm.emergencyContact': { en: 'Emergency contact', es: 'Contacto de emergencia' },
  'employeeForm.emergencyPhone': { en: 'Emergency phone', es: 'Teléfono de emergencia' },
  'employeeForm.selectBank': { en: 'Select bank', es: 'Seleccionar banco' },
  'employeeForm.bank': { en: 'Bank', es: 'Banco' },
  'employeeForm.accountNumber': { en: 'Account number', es: 'Número de cuenta' },
  'employeeForm.accountType': { en: 'Account type', es: 'Tipo de cuenta' },
  'employeeForm.savings': { en: 'Savings', es: 'Ahorros' },
  'employeeForm.checking': { en: 'Checking', es: 'Corriente' },
  'employeeForm.additionalNotes': { en: 'Additional notes', es: 'Notas adicionales' },
  // Address fields
  'employeeForm.address': { en: 'Address', es: 'Dirección' },
  'employeeForm.city': { en: 'City', es: 'Ciudad' },
  'employeeForm.state': { en: 'State', es: 'Estado' },
  'employeeForm.postalCode': { en: 'Postal code', es: 'Código postal' },
  // Generic
  'common.tryAgain': { en: 'Please try again', es: 'Inténtalo nuevamente' },
  'employeeForm.step.personal': { en: 'Personal Information', es: 'Información Personal' },
  'employeeForm.step.employment': { en: 'Employment Information', es: 'Información Laboral' },
  'employeeForm.step.financial': { en: 'Financial Information', es: 'Información Financiera' },
  'employeeForm.step.address': { en: 'Address', es: 'Dirección' },
  'employeeForm.step.banking': { en: 'Banking Information', es: 'Información Bancaria' },
  'employeeForm.stepOf': { en: 'Step {current} of {total}', es: 'Paso {current} de {total}' },
  'employeeForm.detailSubtitle': { en: 'Detailed employee information', es: 'Información detallada del empleado' },
  'employeeForm.registrationFeeTitle': { en: 'Employee Registration Fee', es: 'Tarifa de Registro por Empleado' },
  'employeeForm.registrationFeeDesc': { en: 'A fee of $1 USD per employee per month applies for each registered employee. This monthly fee is billed together with advance commissions.', es: 'Se aplica una tarifa de $1 USD por empleado por mes para cada empleado registrado. Esta tarifa mensual se factura junto con las comisiones de adelantos.' },
  // Common errors
  'common.incompleteInfo': { en: 'Incomplete information', es: 'Información incompleta' },
  'common.fillRequired': { en: 'Please complete all required fields', es: 'Por favor completa todos los campos requeridos' },
  'company.month': { en: '/month', es: '/mes' },
  'company.lastAdvance': { en: 'Last advance:', es: 'Último adelanto:' },
  'company.active': { en: 'Active', es: 'Activo' },
  'company.never': { en: 'Never', es: 'Nunca' },
  'company.advanceReport': { en: 'Advance Report', es: 'Reporte de Adelantos' },
  'company.downloadReport': { en: 'Download the detailed report for your payroll system', es: 'Descarga el reporte detallado para tu sistema de nómina' },
  'company.period': { en: 'Period:', es: 'Período:' },
  'company.includesAll': { en: 'Includes all advances, commissions and deductions', es: 'Incluye todos los adelantos, comisiones y deducciones' },
  'company.downloadCSV': { en: 'Download CSV', es: 'Descargar CSV' },
  'company.usageAnalysis': { en: 'Usage Analysis', es: 'Análisis de Uso' },
  'company.usageStats': { en: 'Usage statistics of advances per employee', es: 'Estadísticas de uso de adelantos por empleado' },
  'company.monthlyAverage': { en: 'Monthly average:', es: 'Promedio mensual:' },
  'company.employeesUse': { en: 'of employees use the platform', es: 'de empleados usan la plataforma' },
  'company.viewFullReport': { en: 'View Full Report', es: 'Ver Reporte Completo' },
  'company.billingPayments': { en: 'Billing and Payments', es: 'Facturación y Pagos' },
  'company.manageBills': { en: 'Manage your bills and pending payments', es: 'Gestiona tus facturas y pagos pendientes' },
  'company.nextInvoice': { en: 'Next Invoice', es: 'Próxima Factura' },
  'company.due': { en: 'Due:', es: 'Vence:' },
  'company.monthlyCommissions': { en: 'Monthly Commissions', es: 'Comisiones Mensuales' },
  'company.activeEmployeesCount': { en: 'active employees', es: 'empleados activos' },
  'company.totalYear': { en: 'Total Year', es: 'Total Año' },
  'company.vsPreviousYear': { en: 'vs previous year', es: 'vs año anterior' },
  'company.recentInvoices': { en: 'Recent Invoices', es: 'Facturas Recientes' },
  'company.invoice': { en: 'Invoice', es: 'Factura' },
  'company.paid': { en: 'Paid', es: 'Pagada' },

  // Operator Dashboard
  'operator.operationsCenter': { en: 'Operations Center', es: 'Centro de Operaciones' },
  'operator.operatorPanel': { en: 'Operator Panel', es: 'Panel del Operador' },
  'operator.pendingAdvancesTitle': { en: 'Pending Advances', es: 'Adelantos Pendientes' },
  'operator.pendingAdvances': { en: 'Pending Advances', es: 'Adelantos Pendientes' },
  'operator.processedBatches': { en: 'Processed Batches', es: 'Lotes Procesados' },
  'operator.confirmationsTab': { en: 'Confirmations', es: 'Confirmaciones' },
  'operator.employeeFeesTab': { en: 'Employee Fees', es: 'Tarifas de Empleados' },
  'operator.selectAdvancesToProcess': { en: 'Select advances to process in the next batch', es: 'Selecciona los adelantos para procesar en el próximo lote' },
  'operator.exportCSV': { en: 'Export CSV', es: 'Exportar CSV' },
  'operator.filter': { en: 'Filter', es: 'Filtrar' },
  'operator.processingDots': { en: 'Processing...', es: 'Procesando...' },
  'operator.processBatch': { en: 'Process Batch', es: 'Procesar Lote' },
  'operator.selectAll': { en: 'Select All', es: 'Seleccionar Todo' },
  'operator.deselectAll': { en: 'Deselect All', es: 'Deseleccionar Todo' },
  'operator.loadingPending': { en: 'Loading pending advances...', es: 'Cargando adelantos pendientes...' },
  'operator.noPending': { en: 'No pending advances', es: 'No hay adelantos pendientes' },
  'operator.allProcessed': { en: 'All advances have been processed', es: 'Todos los adelantos han sido procesados' },
  'operator.unknownEmployee': { en: 'Unknown employee', es: 'Empleado desconocido' },
  'operator.unknownCompany': { en: 'Unknown company', es: 'Empresa desconocida' },
  'operator.feeRateNote': { en: '5% per transaction', es: '5% por transacción' },
  'operator.last3Batches': { en: 'Last 3 batches', es: 'Últimos 3 lotes' },
  'operator.processedBatchesTitle': { en: 'Processed Batches', es: 'Lotes Procesados' },
  'operator.processedBatchesDesc': { en: 'History of processed batches', es: 'Historial de lotes procesados' },
  'operator.loadingBatches': { en: 'Loading processed batches...', es: 'Cargando lotes procesados...' },
  'operator.noProcessedBatches': { en: 'No processed batches', es: 'No hay lotes procesados' },
  'operator.processedBatchesAppear': { en: 'Processed batches will appear here', es: 'Los lotes procesados aparecerán aquí' },
  'operator.unnamedBatch': { en: 'Unnamed batch', es: 'Lote sin nombre' },
  'operator.viewDetails': { en: 'View Details', es: 'Ver Detalles' },
  'operator.uploadSectionTitle': { en: 'Confirm Transfers', es: 'Confirmar Transferencias' },
  'operator.uploadSectionDesc': { en: 'Upload receipts of executed bank transfers', es: 'Subir comprobantes de transferencias realizadas' },
  'operator.uploadCTAButton': { en: 'Upload Receipts', es: 'Subir Comprobantes' },
  'operator.uploadingDots': { en: 'Uploading...', es: 'Subiendo...' },
  'operator.uploadCTATitle': { en: 'Upload Receipts', es: 'Subir Comprobantes' },
  'operator.uploadCTADesc': { en: 'Click the "Upload Receipts" button to start', es: 'Haz clic en el botón "Subir Comprobantes" para comenzar' },
  'operator.confirmationsUploadedTitle': { en: 'Uploaded Confirmations', es: 'Confirmaciones Subidas' },
  'operator.confirmationsUploadedDesc': { en: 'History of uploaded transfer receipts', es: 'Historial de comprobantes de transferencia subidos' },
  'operator.loadingConfirmations': { en: 'Loading confirmations...', es: 'Cargando confirmaciones...' },
  'operator.noConfirmationsSearch': { en: 'No confirmations found', es: 'No se encontraron confirmaciones' },
  'operator.noConfirmations': { en: 'No confirmations uploaded', es: 'No hay confirmaciones subidas' },
  'operator.tryOtherTerms': { en: 'Try different search terms', es: 'Intenta con otros términos de búsqueda' },
  'operator.appearAfterUpload': { en: 'Confirmations will appear here after uploading', es: 'Las confirmaciones aparecerán aquí después de subirlas' },
  'operator.searchConfirmationsPlaceholder': { en: 'Search confirmations...', es: 'Buscar confirmaciones...' },
  'operator.unnamedFile': { en: 'Unnamed file', es: 'Archivo sin nombre' },
  'operator.unknownSize': { en: 'Unknown size', es: 'Tamaño desconocido' },
  'operator.noBatch': { en: 'No batch', es: 'Sin lote' },
  'operator.previewTitle': { en: 'Preview', es: 'Vista Previa' },
  'operator.previewDesc': { en: 'Preview of the selected file', es: 'Vista previa del archivo seleccionado' },
  'operator.openNewTab': { en: 'Open in new tab', es: 'Abrir en nueva pestaña' },
  'operator.previewUnavailable': { en: 'Preview not available', es: 'Vista previa no disponible' },
  'operator.fileHasNoPublicUrl': { en: 'The file has no public URL', es: 'El archivo no tiene URL pública' },
  'operator.deleteConfirmationTitle': { en: 'Delete Confirmation', es: 'Eliminar Confirmación' },
  'operator.deleteConfirmationDesc': { en: 'Are you sure you want to delete this confirmation? This action cannot be undone.', es: '¿Estás seguro de que quieres eliminar esta confirmación? Esta acción no se puede deshacer.' },
  'operator.nextBatch': { en: 'Next batch:', es: 'Próximo lote:' },
  'operator.pendingTransfers': { en: 'Pending Transfers', es: 'Transferencias Pendientes' },
  'operator.totalAmount': { en: 'USD total', es: 'USD total' },
  'operator.processedToday': { en: 'Processed Today', es: 'Procesadas Hoy' },
  'operator.exceptions': { en: 'Exceptions', es: 'Excepciones' },
  'operator.manualAttention': { en: 'Require manual attention', es: 'Requieren atención manual' },
  'operator.reconciliation': { en: 'Reconciliation', es: 'Reconciliación' },
  'operator.unconfirmedBatches': { en: 'Unconfirmed batches', es: 'Lotes sin confirmar' },
  'operator.currentBatch': { en: 'Current Batch', es: 'Lote Actual' },
  'operator.history': { en: 'History', es: 'Historial' },
  'operator.batchTime': { en: 'Batch at', es: 'Lote de las' },
  'operator.preparingTransfers': { en: 'Preparing transfers for next processing', es: 'Preparando transferencias para el próximo procesamiento' },
  'operator.batchProgress': { en: 'Batch progress', es: 'Progreso del lote' },
  'operator.transfers': { en: 'transfers', es: 'transferencias' },
  'operator.generateCSV': { en: 'Generate CSV for Bank', es: 'Generar CSV para Banco' },
  'operator.generatePagoMovil': { en: 'Generate PagoMóvil', es: 'Generar PagoMóvil' },
  'operator.transfersQueue': { en: 'Transfers in Queue', es: 'Transferencias en Cola' },
  'operator.approvedTransfers': { en: 'List of all approved transfers for the next batch', es: 'Lista de todas las transferencias aprobadas para el próximo lote' },
  'operator.transferReconciliation': { en: 'Transfer Reconciliation', es: 'Reconciliación de Transferencias' },
  'operator.confirmTransfers': { en: 'Confirm executed transfers by uploading bank receipts', es: 'Confirma las transferencias ejecutadas subiendo los comprobantes bancarios' },
  'operator.uploadConfirmations': { en: 'Upload Bank Confirmations', es: 'Subir Confirmaciones Bancarias' },
  'operator.dragFile': { en: 'Drag your CSV file here', es: 'Arrastra tu archivo CSV aquí' },
  'operator.clickSelect': { en: 'or click to select', es: 'o haz clic para seleccionar' },
  'operator.selectFile': { en: 'Select File', es: 'Seleccionar Archivo' },
  'operator.pendingConfirmation': { en: 'Batches Pending Confirmation', es: 'Lotes Pendientes de Confirmar' },
  'operator.waiting': { en: 'Waiting', es: 'Esperando' },
  'operator.confirmed': { en: 'Confirmed', es: 'Confirmado' },
  'operator.csvInstructions': { en: 'CSV Format Instructions', es: 'Instrucciones de Formato CSV' },
  'operator.requiredColumns': { en: 'Required columns: reference, amount, status, date', es: 'Columnas requeridas: referencia, monto, estado, fecha' },
  'operator.validStates': { en: 'Valid states: "successful", "failed", "pending"', es: 'Estado válidos: "exitoso", "fallido", "pendiente"' },
  'operator.csvColumns': { en: 'Required columns: reference, amount, status, date', es: 'Columnas requeridas: referencia, monto, estado, fecha' },
  'operator.csvStates': { en: 'Valid states: "successful", "failed", "pending"', es: 'Estados válidos: "exitoso", "fallido", "pendiente"' },
  'operator.csvReference': { en: 'Reference must match transfer ID', es: 'La referencia debe coincidir con el ID de transferencia' },
  'operator.exceptionsHeader': { en: 'Transfers with Exceptions', es: 'Transferencias con Excepciones' },
  'operator.exceptionsDescription': { en: 'Review and resolvWhen logging in, if the registered user enters an incorrect password, display a notification stating that the password is incorrect.e failed transfers', es: 'Revisa y resuelve las transferencias que fallaron' },
  'operator.editButton': { en: 'Edit', es: 'Editar' },
  'operator.retryButton': { en: 'Retry', es: 'Reintentar' },
  'operator.historyTitle': { en: 'Operations History', es: 'Historial de Operaciones' },
  'operator.historyDescription': { en: 'Complete record of all processed batches', es: 'Registro completo de todos los lotes procesados' },
  'operator.exportHistoryButton': { en: 'Export History', es: 'Exportar Historial' },
  'operator.batchTime11': { en: 'Batch 15:00 PM - Today', es: 'Lote 15:00 PM - Hoy' },
  'operator.batchTime15': { en: 'Batch 11:00 AM - Today', es: 'Lote 11:00 AM - Hoy' },
  'operator.completed': { en: 'Completed', es: 'Completado' },

  // Common Dashboard Settings
  'dashboard.settings.title': { en: 'Settings', es: 'Configuración' },
  'dashboard.settings.profile': { en: 'Profile Settings', es: 'Configuración de Perfil' },
  'dashboard.settings.language': { en: 'Language Preferences', es: 'Preferencias de Idioma' },
  'dashboard.settings.notifications': { en: 'Notifications', es: 'Notificaciones' },
  'dashboard.settings.security': { en: 'Security', es: 'Seguridad' },
  'dashboard.settings.account': { en: 'Account Settings', es: 'Configuración de Cuenta' },
  'dashboard.settings.preferences': { en: 'Preferences', es: 'Preferencias' },
  'dashboard.settings.theme': { en: 'Theme', es: 'Tema' },
  'dashboard.settings.privacy': { en: 'Privacy', es: 'Privacidad' },
  'dashboard.settings.billing': { en: 'Billing & Payment', es: 'Facturación y Pago' },
  'dashboard.settings.support': { en: 'Support', es: 'Soporte' },
  'dashboard.settings.documentation': { en: 'Documentation', es: 'Documentación' },
  'dashboard.settings.feedback': { en: 'Feedback', es: 'Comentarios' },
  'dashboard.settings.help': { en: 'Help Center', es: 'Centro de Ayuda' },
  'dashboard.settings.about': { en: 'About', es: 'Acerca de' },

  // Success Messages
  'contact.success.title': { en: 'Message sent!', es: '¡Mensaje enviado!' },
  'contact.success.description': { en: 'Thank you for contacting us. We will respond within the next 4 hours.', es: 'Gracias por contactarnos. Te responderemos en las próximas 4 horas.' },

  // Company Configuration
  'config.title': { en: 'Configuration', es: 'Configuración' },
  'config.subtitle': { en: 'Manage your company settings', es: 'Gestiona la configuración de tu empresa' },
  'config.backToDashboard': { en: 'Back to Dashboard', es: 'Volver al Panel' },
  'config.saveChanges': { en: 'Save Changes', es: 'Guardar Cambios' },
  'config.saving': { en: 'Saving...', es: 'Guardando...' },
  'config.settingsSaved': { en: 'Settings saved', es: 'Configuración guardada' },
  'config.settingsSavedDesc': { en: 'Changes have been applied successfully', es: 'Los cambios han sido aplicados exitosamente' },
  'config.tabs.company': { en: 'Company', es: 'Empresa' },
  'config.tabs.payment': { en: 'Payments', es: 'Pagos' },
  'config.tabs.notifications': { en: 'Notifications', es: 'Notificaciones' },
  'config.tabs.security': { en: 'Security', es: 'Seguridad' },
  'config.tabs.integrations': { en: 'Integrations', es: 'Integraciones' },
  'config.company.title': { en: 'Company Information', es: 'Información de la Empresa' },
  'config.company.subtitle': { en: 'Update your company basic information', es: 'Actualiza los datos básicos de tu empresa' },
  'config.company.businessName': { en: 'Business Name', es: 'Razón Social' },
  'config.company.rif': { en: 'RIF', es: 'RIF' },
  'config.company.email': { en: 'Email', es: 'Correo Electrónico' },
  'config.company.phone': { en: 'Phone', es: 'Teléfono' },
  'config.company.addressTitle': { en: 'Address', es: 'Dirección' },
  'config.company.address': { en: 'Address', es: 'Dirección' },
  'config.company.city': { en: 'City', es: 'Ciudad' },
  'config.company.state': { en: 'State', es: 'Estado' },
  'config.company.postalCode': { en: 'Postal Code', es: 'Código Postal' },
  'config.payment.title': { en: 'Payment Methods', es: 'Métodos de Pago' },
  'config.payment.subtitle': { en: 'Configure payment methods for advances and billing', es: 'Configura los métodos de pago para adelantos y facturación' },
  'config.payment.advanceMethodsTitle': { en: 'Methods for Advances', es: 'Métodos para Adelantos' },
  'config.payment.pagoMovil': { en: 'PagoMóvil', es: 'PagoMóvil' },
  'config.payment.instantPayments': { en: 'Instant payments', es: 'Pagos instantáneos' },
  'config.payment.bankTransfer': { en: 'Bank Transfer', es: 'Transferencia Bancaria' },
  'config.payment.bankVenezuela': { en: 'Banco Venezuela', es: 'Banco Venezuela' },
  // Integrations
  'config.integrations.title': { en: 'Integrations', es: 'Integraciones' },
  'config.integrations.subtitle': { en: 'Connect AvancePay with your existing systems', es: 'Conecta AvancePay con tus sistemas existentes' },
  'config.integrations.payrollSystem': { en: 'Payroll System', es: 'Sistema de Nómina' },
  'config.integrations.payrollSystemDesc': { en: 'Integrate with your payroll system to automate advances', es: 'Integra con tu sistema de nómina para automatizar adelantos' },
  'config.integrations.connect': { en: 'Connect', es: 'Conectar' },
  'config.integrations.notConnected': { en: 'Not Connected', es: 'No Conectado' },
  'config.integrations.bankingApi': { en: 'Banking API', es: 'API Bancaria' },
  'config.integrations.bankingApiDesc': { en: 'Direct integration with banks for transfers', es: 'Integración directa con bancos para transferencias' },
  'config.integrations.connected': { en: 'Connected', es: 'Conectado' },
  'config.integrations.testConnection': { en: 'Test Connection', es: 'Probar Conexión' },
  'config.integrations.hrSystem': { en: 'HR System', es: 'Sistema de RRHH' },
  'config.integrations.hrSystemDesc': { en: 'Connect with your human resources system', es: 'Conéctate con tu sistema de recursos humanos' },
  'config.integrations.configure': { en: 'Configure', es: 'Configurar' },
  'config.integrations.manage': { en: 'Manage', es: 'Gestionar' },
  'config.integrations.customIntegrationTitle': { en: 'Need a custom integration?', es: '¿Necesitas una integración personalizada?' },
  'config.integrations.customIntegrationDesc': { en: 'Our team can help you connect to your existing systems.', es: 'Nuestro equipo puede ayudarte a conectar con tus sistemas existentes.' },
  'config.integrations.contactSupport': { en: 'Contact Support', es: 'Contactar Soporte' },
  'config.payment.active': { en: 'Active', es: 'Activo' },
  'config.payment.configure': { en: 'Configure', es: 'Configurar' },
  'config.payment.commissionsTitle': { en: 'Commission Settings', es: 'Configuración de Comisiones' },
  'config.payment.commissionRate': { en: 'Commission Rate (%)', es: 'Tasa de Comisión (%)' },
  'config.payment.minCommission': { en: 'Minimum Commission (USD)', es: 'Comisión Mínima (USD)' },
  'config.notifications.title': { en: 'Notifications', es: 'Notificaciones' },
  'config.notifications.subtitle': { en: 'Customize how and when to receive notifications', es: 'Personaliza cómo y cuándo recibir notificaciones' },
  'config.notifications.advanceRequestsEmail': { en: 'Advance Requests by Email', es: 'Solicitudes de Adelanto por Email' },
  'config.notifications.advanceRequestsEmailDesc': { en: 'Receive an email when there are new requests', es: 'Recibe un email cuando hay nuevas solicitudes' },
  'config.notifications.advanceRequestsSms': { en: 'Advance Requests by SMS', es: 'Solicitudes de Adelanto por SMS' },
  'config.notifications.advanceRequestsSmsDesc': { en: 'Receive SMS for urgent requests', es: 'Recibe SMS para solicitudes urgentes' },
  'config.notifications.weeklyReports': { en: 'Weekly Reports', es: 'Reportes Semanales' },
  'config.notifications.weeklyReportsDesc': { en: 'Weekly activity summary', es: 'Resumen semanal de actividad' },
  'config.notifications.billingNotifications': { en: 'Billing Notifications', es: 'Notificaciones de Facturación' },
  'config.notifications.billingNotificationsDesc': { en: 'Payment and invoice reminders', es: 'Recordatorios de pagos y facturas' },
  'config.notifications.pushNotifications': { en: 'Push Notifications', es: 'Notificaciones Push' },
  'config.notifications.pushNotificationsDesc': { en: 'Real-time notifications in the browser', es: 'Notificaciones en tiempo real en el navegador' },
  'config.security.title': { en: 'Security', es: 'Seguridad' },
  'config.security.subtitle': { en: 'Configure security options for your account', es: 'Configura las opciones de seguridad para tu cuenta' },
  'config.security.twoFactorAuth': { en: 'Two-Factor Authentication', es: 'Autenticación de Dos Factores' },
  'config.security.twoFactorAuthDesc': { en: 'Add an extra layer of security', es: 'Añade una capa extra de seguridad' },
  'config.security.loginNotifications': { en: 'Login Notifications', es: 'Notificaciones de Inicio de Sesión' },
  'config.security.loginNotificationsDesc': { en: 'Email when someone accesses your account', es: 'Email cuando alguien accede a tu cuenta' },
  'config.security.sessionTimeout': { en: 'Session Timeout (minutes)', es: 'Tiempo de Sesión (minutos)' },
  'config.security.approvalAmount': { en: 'Required Approval Amount (USD)', es: 'Monto de Aprobación Requerida (USD)' },

  // Company Dashboard - Billing and Payments
  'company.billing.totalOutstanding': { en: 'Total Outstanding', es: 'Total a Pagar' },
  'company.billing.dueDate': { en: 'Due:', es: 'Vence:' },
  'company.billing.monthlyAdvances': { en: 'Monthly Advances', es: 'Adelantos del Mes' },
  'company.billing.registrationFees': { en: 'Registration Fees', es: 'Tarifas de Registro' },
  'company.billing.registeredEmployees': { en: 'registered employees', es: 'empleados registrados' },
  'company.totalBilling': { en: 'Total Billing', es: 'Total Facturación' },
  'company.billing.payNow': { en: 'Pay Now', es: 'Pagar Ahora' },
  'company.billing.downloadInvoice': { en: 'Download Invoice', es: 'Descargar Factura' },
  'company.billing.paymentHistory': { en: 'Payment History', es: 'Historial de Pagos' },
  'company.billing.recentInvoices': { en: 'Recent invoices and payments', es: 'Facturas y pagos recientes' },
  'company.billing.noPayments': { en: 'No payments found', es: 'No se encontraron pagos' },
  'company.billing.paymentMethod': { en: 'Payment Method', es: 'Método de Pago' },
  'company.billing.paymentDetails': { en: 'Payment Details', es: 'Detalles del Pago' },
  'company.billing.processPayment': { en: 'Process Payment', es: 'Procesar Pago' },
  'company.billing.processing': { en: 'Processing...', es: 'Procesando...' },
  'company.billing.paymentProcessed': { en: 'Payment Processed Successfully', es: 'Pago Procesado Exitosamente' },
  'company.billing.paymentProcessedDesc': { en: 'The payment has been processed and values have been updated locally.', es: 'Se ha procesado el pago y los valores se han actualizado localmente.' },
  'company.billing.paymentError': { en: 'Payment Error', es: 'Error de Pago' },
  'company.billing.paymentErrorDesc': { en: 'There was an error processing the payment. Please try again.', es: 'Hubo un error al procesar el pago. Por favor intenta de nuevo.' },
  'company.billing.bankTransfer': { en: 'Bank Transfer', es: 'Transferencia Bancaria' },
  'company.billing.pagoMovil': { en: 'PagoMóvil', es: 'PagoMóvil' },
  'company.billing.creditCard': { en: 'Credit Card', es: 'Tarjeta de Crédito' },
  'company.billing.amountBreakdown': { en: 'Amount Breakdown', es: 'Desglose del Monto' },
  'company.billing.advances': { en: 'Advances:', es: 'Adelantos:' },
  'company.billing.registrationFeesLabel': { en: 'Registration Fees:', es: 'Tarifas de Registro:' },
  'company.billing.totalToPay': { en: 'Total to Pay:', es: 'Total a Pagar:' },
  'company.billing.lastPayment': { en: 'Last Payment', es: 'Último Pago' },
  'company.billing.nextDue': { en: 'Next Due', es: 'Próximo Vencimiento' },
  'company.billing.refresh': { en: 'Refresh', es: 'Actualizar' },
  'company.billing.refreshDesc': { en: 'Refresh company data', es: 'Actualizar datos de la empresa' },
  'company.billing.billingDetails': { en: 'Billing Details', es: 'Detalles de Facturación' },
  'company.billing.billingDetailsDesc': { en: 'Breakdown of commissions and fees for the current period', es: 'Desglose de comisiones y tarifas del período actual' },
  'company.billing.advanceCommissions': { en: 'Advance Commissions', es: 'Comisiones por Adelantos' },
  'company.billing.processedAdvances': { en: 'Processed advances', es: 'Adelantos procesados' },
  'company.billing.totalAdvancesAmount': { en: 'Total advances amount', es: 'Monto total adelantos' },
  'company.billing.averageCommission': { en: 'Average commission', es: 'Comisión promedio' },
  'company.billing.feePerEmployee': { en: 'Fee per employee', es: 'Tarifa por empleado' },
  'company.billing.monthlyFee': { en: 'Monthly fee', es: 'Tarifa mensual' },
  'company.billing.activeEmployees': { en: 'Active employees', es: 'Empleados activos' },
  'company.billing.totalFees': { en: 'Total fees', es: 'Total tarifas' },
  'company.billing.dataUpdated': { en: 'Data Updated', es: 'Datos Actualizados' },
  'company.billing.dataUpdatedDesc': { en: 'Company data has been updated', es: 'Los datos de la empresa se han actualizado' },
  'company.billing.loadingPayments': { en: 'Loading payments...', es: 'Cargando pagos...' },
  'company.billing.paymentStatus': { en: 'Status', es: 'Estado' },
  'company.billing.paid': { en: 'Paid', es: 'Pagado' },
  'company.billing.pending': { en: 'Pending', es: 'Pendiente' },
  'company.billing.amount': { en: 'Amount', es: 'Monto' },
  'company.billing.date': { en: 'Date', es: 'Fecha' },
  'company.billing.invoiceNumber': { en: 'Invoice #', es: 'Factura #' },
  'company.billing.period': { en: 'Period', es: 'Período' },
  'company.billing.pay': { en: 'Pay', es: 'Pagar' },
  'company.billing.estimatedAmount': { en: 'Estimated amount:', es: 'Monto estimado:' },
  'company.billing.daysRemaining': { en: 'Days remaining:', es: 'Días restantes:' },
  'company.billing.modalState': { en: 'Modal State:', es: 'Estado del Modal:' },
  'company.billing.realTotal': { en: 'Real Total:', es: 'Total Real:' },
  'company.billing.advancesAmount': { en: 'Advances:', es: 'Adelantos:' },
  'company.billing.feesAmount': { en: 'Fees:', es: 'Tarifas:' },
  'company.billing.completePaymentData': { en: 'Complete the data to process the payment of', es: 'Completa los datos para procesar el pago de' },
  'company.billing.enterPaymentDetails': { en: 'Enter payment details', es: 'Ingresa los detalles del pago' },
  'company.billing.enterPaymentMethod': { en: 'Select payment method', es: 'Selecciona el método de pago' },
  'company.billing.cancel': { en: 'Cancel', es: 'Cancelar' },
  'company.billing.close': { en: 'Close', es: 'Cerrar' },
  'company.billing.open': { en: 'Open', es: 'Abrir' },
  'company.billing.employeeAdded': { en: 'Employee Added Successfully', es: 'Empleado Agregado Exitosamente' },
  'company.billing.employeeAddedDesc': { en: 'An activation code has been sent and a $1 USD registration fee has been added for this employee.', es: 'Se ha enviado un código de activación y se ha agregado una tarifa de registro de $1 USD por este empleado.' },
  'company.billing.employeeDeleted': { en: 'Employee Deleted', es: 'Empleado Eliminado' },
  'company.billing.employeeDeletedDesc': { en: 'was deleted successfully', es: 'fue eliminado correctamente' },
  'company.billing.employeeActivated': { en: 'Employee Activated', es: 'Empleado Activado' },
  'company.billing.employeeActivatedDesc': { en: 'has activated their account', es: 'ha activado su cuenta' },
  'company.billing.employeeDeactivated': { en: 'Employee Deactivated', es: 'Empleado Desactivado' },
  'company.billing.employeeDeactivatedDesc': { en: 'has been deactivated', es: 'ha sido desactivado' },
  'company.billing.employeeVerified': { en: 'Employee Verified', es: 'Empleado Verificado' },
  'company.billing.employeeVerifiedDesc': { en: 'has been verified successfully', es: 'ha sido verificado exitosamente' },
  'company.billing.newEmployeeAdded': { en: 'New Employee Added', es: 'Nuevo Empleado Agregado' },
  'company.billing.newEmployeeAddedDesc': { en: 'has been added to the company', es: 'ha sido agregado a la empresa' },
  'company.billing.listUpdated': { en: 'List Updated', es: 'Lista Actualizada' },
  'company.billing.listUpdatedDesc': { en: 'The employee list has been updated', es: 'La lista de empleados ha sido actualizada' },
  'company.billing.invalidEmail': { en: 'Invalid Email', es: 'Email Inválido' },
  'company.billing.invalidEmailDesc': { en: 'Enter a valid email address', es: 'Ingresa una dirección de correo válida' },
  'company.billing.duplicateEmail': { en: 'Duplicate Email', es: 'Correo Duplicado' },
  'company.billing.duplicateEmailDesc': { en: 'This email is already registered for a company employee.', es: 'Este correo ya está registrado para un empleado de la empresa.' },
  'company.billing.error': { en: 'Error', es: 'Error' },
  'company.billing.couldNotLoadEmployees': { en: 'Could not load employees', es: 'No se pudieron cargar los empleados' },
  'company.billing.couldNotUpdateEmployees': { en: 'Could not update employees', es: 'No se pudieron actualizar los empleados' },
  'company.billing.couldNotAddEmployee': { en: 'Could not add employee', es: 'No se pudo agregar el empleado' },
  'company.billing.couldNotDeleteEmployee': { en: 'Could not delete employee', es: 'No se pudo eliminar el empleado' },
  'company.billing.couldNotLoadPayments': { en: 'Could not load payment history', es: 'No se pudo cargar el historial de pagos' },
  'company.billing.totalBilling': { en: 'Total Billing', es: 'Facturación Total' },
  'company.billing.firstPeriod': { en: 'First Period (1-15th)', es: 'Primer Período (1-15)' },
  'company.billing.secondPeriod': { en: 'Second Period (16th-end)', es: 'Segundo Período (16-fin)' },
  'company.billing.currentPeriod': { en: 'Current Period', es: 'Período Actual' },
  'company.billing.employeeFees': { en: 'Employee Fees ($1/employee)', es: 'Tarifas de Empleados ($1/empleado)' },
  'company.billing.advancesFees': { en: 'Advances Fees', es: 'Tarifas de Adelantos' },
  'company.billing.firstHalf': { en: 'First half (1-15th):', es: 'Primera mitad (1-15):' },
  'company.billing.secondHalf': { en: 'Second half (16th-end):', es: 'Segunda mitad (16-fin):' },
  'company.billing.feePerEmployeeMonth': { en: 'Fee per employee:', es: 'Tarifa por empleado:' },
  // Operator - Employee Fees section
  'operator.employeeFeesTitle': { en: 'Monthly Employee Fees', es: 'Tarifas Mensuales de Empleados' },
  'operator.employeeFeesDesc': { en: 'Manage the monthly $1 USD fee per each active employee charged to companies.', es: 'Gestiona las tarifas mensuales de $1 USD por cada empleado activo cobradas a las empresas.' },
  'operator.activeEmployees': { en: 'active employees', es: 'empleados activos' },
  'operator.monthlyFee': { en: 'Monthly fee', es: 'Tarifa mensual' },
  'company.billing.monthlyEmployeeFees': { en: 'Monthly Employee Fees', es: 'Tarifas Mensuales de Empleados' },
  'operator.noEmployeeFees': { en: 'No employee fees found.', es: 'No hay tarifas de empleados registradas.' },
  'operator.overdue': { en: 'Overdue', es: 'Vencido' },
  // Company Dashboard - additional UI strings
  'company.deleteEmployeeTitle': { en: 'Delete employee', es: 'Eliminar empleado' },
  'company.deleteEmployeeConfirm': { en: 'Are you sure you want to delete {name}? This action cannot be undone.', es: '¿Seguro que deseas eliminar a {name}? Esta acción no se puede deshacer.' },
  'company.exportConfirmTitle': { en: 'Confirm export', es: 'Confirmar exportación' },
  'company.exportConfirmDesc': { en: 'Do you want to export the selected content in the chosen format?', es: '¿Deseas exportar el contenido seleccionado en el formato elegido?' },
  'company.noEmployees': { en: 'No employees registered', es: 'No hay empleados registrados' },
  'company.addFirstEmployeeHint': { en: 'Add your first employee using the "Add Employee" button', es: 'Agrega tu primer empleado usando el botón "Agregar Empleado"' },
  'company.recentReports': { en: 'Recent Reports', es: 'Reportes Recientes' },
  // Company Dashboard - Recent Reports subsection
  'company.reports.historyDesc': { en: 'History of generated reports', es: 'Historial de reportes generados' },
  'company.reports.noReports': { en: 'No reports generated yet', es: 'No hay reportes generados aún' },
  'company.approveAdvanceTitle': { en: 'Approve Advance', es: 'Aprobar Adelanto' },
  'company.rejectAdvanceDescPrefix': { en: 'Are you sure you want to reject this advance of', es: '¿Estás seguro de que quieres rechazar este adelanto de' },
  'common.actionCannotBeUndone': { en: 'This action cannot be undone.', es: 'Esta acción no se puede deshacer.' },
  'company.approveAdvanceDescPrefix': { en: 'Do you want to approve this advance?', es: '¿Deseas aprobar este adelanto?' },
  'company.approveAdvanceDescF': { en: 'This action will mark the advance as approved.', es: 'Esta acción marcará el adelanto como aprobado.' },
  'company.approveAdvanceNoteApproved': { en: 'Note: Once approved, it will be included in the next batch.', es: 'Nota: Una vez aprobado, se incluirá en el próximo lote.' },
  'company.confirmCancelAdvance': { en: 'Confirm cancellation', es: 'Confirmar cancelación' },
  'company.cancelAdvanceDescPrefix': { en: 'Are you sure you want to cancel this advance?', es: '¿Seguro que deseas cancelar este adelanto?' },
};

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get from localStorage or default to Spanish (Venezuelan market)
    const saved = localStorage.getItem('language') as Language;
    return saved || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    return translation[language] || translation.es || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};