name: Exchange Rate Updates

on:
  schedule:
    # Real-time updates every 15 minutes
    - cron: '*/15 * * * *'
    # Hourly backup updates
    - cron: '0 * * * *'
    # Daily backup at 6 PM Venezuela time (22:00 UTC)
    - cron: '0 22 * * *'
    # Status monitoring every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  realtime-update:
    if: github.event.schedule == '*/15 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Real-time Exchange Rate Update (15 min)
        run: |
          curl -X POST ${{ secrets.SUPABASE_FUNCTION_URL }}/realtime-exchange-update \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"

  hourly-update:
    if: github.event.schedule == '0 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Hourly Exchange Rate Backup
        run: |
          curl -X POST ${{ secrets.SUPABASE_FUNCTION_URL }}/hourly-exchange-update \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"

  daily-backup:
    if: github.event.schedule == '0 22 * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Daily Exchange Rate Backup
        run: |
          curl -X POST ${{ secrets.SUPABASE_FUNCTION_URL }}/daily-exchange-update \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"
  status-check:
    if: github.event.schedule == '*/30 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check Exchange Rate Status
        run: |
          curl -X POST ${{ secrets.SUPABASE_FUNCTION_URL }}/check-exchange-rate-status \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"

